minimum_pre_commit_version: 4.3.0
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        additional_dependencies: [setuptools]
        name: isort (python)

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [--line-length=120]

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: qmlformat
        name: Format QML files
        entry: bash -c 'for file in "$@"; do qmlformat -i "$file" && rm -f "${file}~"; done' --
        language: system
        files: \.qml$
        pass_filenames: true
