name: Publish Sealed

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Pull Clickable Docker image
        run: |
          docker pull clickable/ci-20.04-arm64:latest

      - name: Initialize submodules
        run: |
          docker run --rm \
            --volume ./:/app \
            --workdir /app \
            clickable/ci-20.04-arm64:latest \
            bash -c "git config --global --add safe.directory '*' && git submodule update --init --recursive"

      - name: Build libraries
        run: |
          docker run --rm \
            --volume ./:/app \
            --workdir /app \
            clickable/ci-20.04-arm64:latest \
            bash -c "clickable build --libs --arch arm64"

      - name: Build application
        run: |
          docker run --rm \
            --volume ./:/app \
            --workdir /app \
            clickable/ci-20.04-arm64:latest \
            bash -c "clickable build --arch arm64 --skip-review"

      - name: List build outputs
        run: |
          echo "=== Root directory .click files ==="
          find . -name "*.click" -type f 2>/dev/null || echo "No .click files found in root"
          echo "=== All .click files ==="
          find . -name "*.click" -type f 2>/dev/null || echo "No .click files found anywhere"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sealed-arm64-click-package
          path: |
            *.click
            build/**/*.click
          retention-days: 30

